services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      #- ./app:/code/app
      #- ./tests:/code/tests
      - .:/code
      - ./weights:/code/weights
    env_file:
      - .env
